UPSTREAM: drm/amd/display: mark dml31's UseMinimumDCFCLK() as noinline_for_stack
clang reports:
drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn31/display_mode_vba_31.c:3797:6: error: stack frame size (2632) exceeds limit (2048) in 'dml31_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
 3797 | void dml31_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
      |      ^
1 error generated.

So, since UseMinimumDCFCLK() consumes a lot of stack space, mark it as
noinline_for_stack to prevent it from blowing up
dml31_ModeSupportAndSystemConfigurationFull()'s stack size.

Acked-by: Alex Deucher <alexander.deucher@amd.com>
Signed-off-by: Hamza Mahfooz <hamza.mahfooz@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit caf0f98dc280b5426b1858d4e70130aa3dd9679c)

BUG=b:360259337
TEST=USE=buildtest emerge-amd64-generic chromeos-kernel-5_15

Change-Id: Ie00fae5393ca73632c758fcd9ad2eb3b1644f874
Signed-off-by: George Burgess IV <gbiv@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5796577
Commit-Queue: George Burgess <gbiv@chromium.org>
Reviewed-by: Brian Norris <briannorris@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>